# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d41f65f753168bafe1086dcd0c4d495c9b1b9bccaf5e6598ec72751d7c1534503647931af3cb10a3c2630201f62b0f821d2e8cb6721417a3f10443c60e84305

test:
  secret_key_base: 0096b3959c7fefd974dcc054004895daec527a057dd167d5351ebfd14a556739a12898546ed1bc9e632025bc4b280d7fa5a713c1734a5a7042dc4358a121bd29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
